name: GitHub Actions Build and Deploy Gitbook
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install
      run: |
        sudo npm install -g gitbook-cli
        gitbook install

    - name: Build
      run: |
        gitbook build

    - name: Add Nojekyll
      run: |
        touch _book/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: _book